---
production: &default
  serverPort: 3333
  baseUrl: http://www.makingdevelopers.com
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    minify: true
    css:
      stylusPrecompile: true
      compress: true
  app:
    default: blog
  languages:
    default: en
    list: [en, es]
  database:
    mysql:
      host: localhost
      user: root
      password: '123456'
      database: makingdevelopers
      port: 3306
      debug: true
      socket: /var/mysql/mysql.sock

stage: &stage
  <<: *default
  baseUrl: http://stage.makingdevelopers.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.makingdevelopers.com

development:
  <<: *latest
  baseUrl: http://local.makingdevelopers.com
  html:
    minify: false
    css:
      stylusPrecompile: false
      compress: false
